name: ğŸ”„ Reopen Closed Issues
on:
  issue_comment:
    types: [created]

jobs:
  reopen:
    runs-on: ubuntu-latest
    if: github.event.issue.state == 'closed' && github.repository == 'BrycensRanch/gpu-screen-recorder-git-copr'
    
    steps:
      - name: Look for Reopen Phrase
        id: check_phrase
        run: |
          LOWERCASE_COMMENT=$(echo "${{ github.event.comment.body }}" | tr '[:upper:]' '[:lower:]')
          LOOSE_PATTERN="(i think |)you[']?ve made a mistake,.*(robot|bot|copilot)"
          
          if [[ $LOWERCASE_COMMENT =~ $LOOSE_PATTERN ]]; then
              echo "Reopen phrase detected."
              echo "REOPEN_ISSUE=true" >> $GITHUB_ENV
          fi
      - name: Reopen Issue
        if: env.REOPEN_ISSUE == 'true'
        uses: actions/github-script@v7
        with:
          script: |
            const issue_number = context.issue.number;
            
            await github.rest.issues.update({
              issue_number: issue_number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open'
            });

            await github.rest.issues.createComment({
              issue_number: issue_number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `ğŸ‘ŒğŸ¿ It is done.`
            });